// PR_REGIONS is the Plate Recognizer region code list used in the device PR
// config panel's dropdown (#5 follow-up A). Mirrors the Edge UI's list
// (mac-mini-rollout/webui/templates/setup.html) so the two surfaces agree.
export interface PRRegion {
  code: string;
  label: string;
}

export const PR_REGIONS: PRRegion[] = [
  { code: "us-al", label: "Alabama (us-al)" },
  { code: "us-ak", label: "Alaska (us-ak)" },
  { code: "us-az", label: "Arizona (us-az)" },
  { code: "us-ar", label: "Arkansas (us-ar)" },
  { code: "us-ca", label: "California (us-ca)" },
  { code: "us-co", label: "Colorado (us-co)" },
  { code: "us-ct", label: "Connecticut (us-ct)" },
  { code: "us-de", label: "Delaware (us-de)" },
  { code: "us-fl", label: "Florida (us-fl)" },
  { code: "us-ga", label: "Georgia (us-ga)" },
  { code: "us-hi", label: "Hawaii (us-hi)" },
  { code: "us-id", label: "Idaho (us-id)" },
  { code: "us-il", label: "Illinois (us-il)" },
  { code: "us-in", label: "Indiana (us-in)" },
  { code: "us-ia", label: "Iowa (us-ia)" },
  { code: "us-ks", label: "Kansas (us-ks)" },
  { code: "us-ky", label: "Kentucky (us-ky)" },
  { code: "us-la", label: "Louisiana (us-la)" },
  { code: "us-me", label: "Maine (us-me)" },
  { code: "us-md", label: "Maryland (us-md)" },
  { code: "us-ma", label: "Massachusetts (us-ma)" },
  { code: "us-mi", label: "Michigan (us-mi)" },
  { code: "us-mn", label: "Minnesota (us-mn)" },
  { code: "us-ms", label: "Mississippi (us-ms)" },
  { code: "us-mo", label: "Missouri (us-mo)" },
  { code: "us-mt", label: "Montana (us-mt)" },
  { code: "us-ne", label: "Nebraska (us-ne)" },
  { code: "us-nv", label: "Nevada (us-nv)" },
  { code: "us-nh", label: "New Hampshire (us-nh)" },
  { code: "us-nj", label: "New Jersey (us-nj)" },
  { code: "us-nm", label: "New Mexico (us-nm)" },
  { code: "us-ny", label: "New York (us-ny)" },
  { code: "us-nc", label: "North Carolina (us-nc)" },
  { code: "us-nd", label: "North Dakota (us-nd)" },
  { code: "us-oh", label: "Ohio (us-oh)" },
  { code: "us-ok", label: "Oklahoma (us-ok)" },
  { code: "us-or", label: "Oregon (us-or)" },
  { code: "us-pa", label: "Pennsylvania (us-pa)" },
  { code: "us-ri", label: "Rhode Island (us-ri)" },
  { code: "us-sc", label: "South Carolina (us-sc)" },
  { code: "us-sd", label: "South Dakota (us-sd)" },
  { code: "us-tn", label: "Tennessee (us-tn)" },
  { code: "us-tx", label: "Texas (us-tx)" },
  { code: "us-ut", label: "Utah (us-ut)" },
  { code: "us-vt", label: "Vermont (us-vt)" },
  { code: "us-va", label: "Virginia (us-va)" },
  { code: "us-wa", label: "Washington (us-wa)" },
  { code: "us-wv", label: "West Virginia (us-wv)" },
  { code: "us-wi", label: "Wisconsin (us-wi)" },
  { code: "us-wy", label: "Wyoming (us-wy)" },
  { code: "us-dc", label: "Washington DC (us-dc)" },
];
