package agentmanifest

import (
	"crypto/ed25519"
	_ "embed"
	"encoding/base64"
	"strings"
)

// releasePubKeyB64 is the base64 Ed25519 public key the agent verifies release
// manifests against, baked into the build. Generated by
// cmd/agent-manifest-keygen; the matching private key is the CI secret
// AGENT_MANIFEST_SIGNING_KEY. The committed value is a DEV key — rotate before
// production (regenerate, commit the new public key, set the new secret).
//
//go:embed release_pubkey.b64
var releasePubKeyB64 string

// ReleasePublicKey returns the baked-in release public key. It panics if the
// embedded key is malformed — a build-time misconfiguration that should fail
// fast, not surface as a silent verification failure on a device.
func ReleasePublicKey() ed25519.PublicKey {
	raw, err := base64.StdEncoding.DecodeString(strings.TrimSpace(releasePubKeyB64))
	if err != nil || len(raw) != ed25519.PublicKeySize {
		panic("agentmanifest: embedded release_pubkey.b64 is not a valid ed25519 public key")
	}
	return ed25519.PublicKey(raw)
}

// VerifyRelease verifies a manifest against the baked-in release public key —
// the call the agent makes before installing a binary.
func VerifyRelease(m Manifest) error {
	return Verify(ReleasePublicKey(), m)
}
