package cmdsign

import (
	"crypto/ed25519"
	_ "embed"
	"encoding/base64"
	"strings"

	"github.com/emilejacobs/control-plane/internal/envelope"
)

// commandPubKeyB64 is the base64 Ed25519 public key the agent verifies
// downward command signatures against, baked into the build. Generated by
// cmd/agent-manifest-keygen; the matching PRIVATE key is loaded by cp-api /
// cp-ingest from Secrets Manager (secret id CP_COMMAND_SIGNING_SECRET_ID) and
// used to sign in-process. The committed value is a DEV key — rotate before
// production (regenerate, commit the new public key, set the new secret).
//
//go:embed command_pubkey.b64
var commandPubKeyB64 string

// CommandPublicKey returns the baked-in command public key. It panics if the
// embedded key is malformed — a build-time misconfiguration that should fail
// fast, not surface as a silent verification failure on a device.
func CommandPublicKey() ed25519.PublicKey {
	raw, err := base64.StdEncoding.DecodeString(strings.TrimSpace(commandPubKeyB64))
	if err != nil || len(raw) != ed25519.PublicKeySize {
		panic("cmdsign: embedded command_pubkey.b64 is not a valid ed25519 public key")
	}
	return ed25519.PublicKey(raw)
}

// VerifyCommand verifies a command against the baked-in command public key —
// the call the agent dispatcher makes before executing a signature-required
// command.
func VerifyCommand(cmd envelope.Command) error {
	return Verify(CommandPublicKey(), cmd)
}
