package main

import (
	"io"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

// TestStaticHandler_ServesIndexAtRoot ensures the embed.FS lookup
// resolves edge-ui/out/index.html for "/".
func TestStaticHandler_ServesIndexAtRoot(t *testing.T) {
	h := StaticHandler(staticFS)
	srv := httptest.NewServer(h)
	defer srv.Close()

	resp, err := http.Get(srv.URL + "/")
	if err != nil {
		t.Fatalf("Get: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		t.Fatalf("status: %d", resp.StatusCode)
	}
	body, _ := io.ReadAll(resp.Body)
	if !strings.Contains(string(body), "uKnomi Edge") {
		t.Fatalf("body did not contain 'uKnomi Edge' (likely not index.html): %s", truncate(body, 200))
	}
}

// TestStaticHandler_SPAFallbackToPreviewPlaceholder ensures any
// /preview/<id> URL is served the **preview placeholder** HTML —
// NOT root index.html. Bench smoke 2026-05-26 surfaced this: the
// original SPA fallback always served root index.html, so
// /preview/cam1 rendered "uKnomi Edge / Device-local Edge UI"
// instead of PreviewClient, and the <img> never reached the DOM.
//
// The placeholder lives at edge-ui-out/preview/_.html (Next.js
// generates it from generateStaticParams returning [{cameraId: "_"}])
// and contains the PreviewClient pre-rendered HTML; the client side
// re-reads window.location.pathname on hydration so the build-time
// "_" gets replaced with the real cameraId at runtime.
func TestStaticHandler_SPAFallbackToPreviewPlaceholder(t *testing.T) {
	h := StaticHandler(staticFS)
	srv := httptest.NewServer(h)
	defer srv.Close()

	resp, err := http.Get(srv.URL + "/preview/cam-runtime-id")
	if err != nil {
		t.Fatalf("Get: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		t.Fatalf("status: %d", resp.StatusCode)
	}
	body, _ := io.ReadAll(resp.Body)
	bs := string(body)

	// Preview-placeholder markers (PreviewClient rendered statically):
	if !strings.Contains(bs, "Camera live preview") {
		t.Errorf("response missing 'Camera live preview' marker — likely served root index.html: %s",
			truncate(body, 300))
	}
	// Root-page-only markers (must NOT appear):
	if strings.Contains(bs, "Device-local Edge UI") {
		t.Errorf("response contains root-page 'Device-local Edge UI' tagline — SPA fell back to / instead of /preview/_.html")
	}
}

// TestStaticHandler_AssetServed ensures actual built assets (e.g.
// _next/static/*.js) are served from the embed, not the SPA fallback.
// We don't pin a specific filename — next build produces hashed names
// — but we assert that requesting a known directory yields a 404 or a
// real file (not the HTML body).
func TestStaticHandler_AssetServedNotFallback(t *testing.T) {
	h := StaticHandler(staticFS)
	srv := httptest.NewServer(h)
	defer srv.Close()

	// _not-found.html is generated by next build and exists at the
	// repo's out/ root. Requesting it must return the actual file
	// (not be rewritten to index.html via SPA fallback).
	resp, err := http.Get(srv.URL + "/_not-found.html")
	if err != nil {
		t.Fatalf("Get: %v", err)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	if strings.Contains(string(body), "uKnomi Edge") &&
		strings.Contains(string(body), "Open a Camera live preview") {
		t.Fatalf("/_not-found.html was served index.html via SPA fallback (it should not be)")
	}
}

// TestStaticHandler_DoesNotCatchAPIStream ensures the static handler
// doesn't claim /preview/<id>/stream — that path belongs to the API
// (PreviewHandler from internal/edgeui). When both are wired into the
// same mux, the API must win.
func TestStaticHandler_APIWinsOnStreamSuffix(t *testing.T) {
	// Wire static + a sentinel API handler so we can assert the API
	// wins for /preview/<id>/stream. The sentinel matches anything
	// ending in /stream; the static handler matches everything else.
	mux := http.NewServeMux()
	mux.HandleFunc("/preview/", func(w http.ResponseWriter, r *http.Request) {
		if strings.HasSuffix(r.URL.Path, "/stream") {
			w.WriteHeader(http.StatusOK)
			w.Write([]byte("API:" + r.URL.Path))
			return
		}
		StaticHandler(staticFS).ServeHTTP(w, r)
	})
	mux.Handle("/", StaticHandler(staticFS))

	srv := httptest.NewServer(mux)
	defer srv.Close()

	resp, err := http.Get(srv.URL + "/preview/cam1/stream")
	if err != nil {
		t.Fatalf("Get: %v", err)
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	if !strings.HasPrefix(string(body), "API:") {
		t.Fatalf("/stream URL must be served by the API, not the static handler: %s", body)
	}
}

func truncate(b []byte, n int) string {
	if len(b) > n {
		return string(b[:n]) + "…"
	}
	return string(b)
}
